name: Test Workflow
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Log hello world
              run: echo "hello world"

            - name: Log node version
              run: node -v
